export enum TaskStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  UNDER_REVIEW = "UNDER_REVIEW",
  COMPLETED = "COMPLETED",
  BLOCKED = "BLOCKED",
  REJECTED = "REJECTED",
  REOPENED = "REOPENED",
}

export enum TaskPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum TaskActionType {
  TASK_CREATED = "TASK_CREATED",
  TASK_UPDATED = "TASK_UPDATED",
  TASK_ASSIGNED = "TASK_ASSIGNED",
  TASK_REASSIGNED = "TASK_REASSIGNED",
  TASK_COMPLETED = "TASK_COMPLETED",
  TASK_APPROVED = "TASK_APPROVED",
  TASK_REJECTED = "TASK_REJECTED",
  COMMENT_ADDED = "COMMENT_ADDED",
}
